# Generated by Django 4.1.7 on 2023-04-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthworker',
            name='health_center',
            field=models.CharField(choices=[('HC1', 'Health Center 1'), ('HC2', 'Health Center 2'), ('HC3', 'Health Center 3'), ('HC4', 'Health Center 4'), ('HC5', 'Health Center 5'), ('HC6', 'Health Center 6')], max_length=3),
        ),
    ]
